const { chromium } = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright' : 'playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844}});
 const page=await context.newPage();const requests=[];const errors=[];
 page.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postData()}));
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:5173');
 assert.equal(await page.locator('input[type=file]').count(),0);
 assert.equal(await page.locator('#send').isDisabled(),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.evaluate(()=>{localStorage.setItem('aic-local-prototype-v1',JSON.stringify([{role:'user',content:'FICTIEVE-PRIVACY-TEST-48219'}]));});
 await page.reload();
 assert.match(await page.locator('#messages').innerText(),/FICTIEVE-PRIVACY-TEST-48219/);
 assert.equal(await page.locator('#remember').isChecked(),true);
 await page.locator('#remember').uncheck();
 assert.equal(await page.evaluate(()=>localStorage.getItem('aic-local-prototype-v1')),null);
 await page.locator('#remember').check();await page.reload();
 assert.match(await page.locator('#messages').innerText(),/FICTIEVE-PRIVACY-TEST-48219/);
 await page.locator('#clear').click();await page.reload();
 assert.equal(await page.locator('#messages').innerText(),'');
 await page.evaluate(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['test'],'screenshot.png',{type:'image/png'}));document.dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));});
 assert.match(await page.locator('#error').innerText(),/niet aangenomen/);
 await page.evaluate(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['test'],'screenshot.png',{type:'image/png'}));document.getElementById('input').dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));});
 assert.match(await page.locator('#error').innerText(),/Screenshots/);
 const gpu=await page.evaluate(()=>({available:!!navigator.gpu}));
 await page.locator('#start').click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('kon niet')||document.querySelector('#status').textContent.includes('klaar'),null,{timeout:45000}).catch(()=>{});
 assert.equal(requests.some(r=>JSON.stringify(r).includes('FICTIEVE-PRIVACY-TEST-48219')),false);
 console.log(JSON.stringify({checks:'mobile layout, no file inputs, opt-in storage, reload, delete, paste/drop rejection, no seeded chat in requests',gpu,status:await page.locator('#status').innerText(),errors,externalRequests:requests.filter(r=>!r.url.startsWith('http://localhost')&&!r.url.startsWith('ws://localhost'))},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
